### ISSUE TITLE
Dist plot: Does not work to snapshot a dist plot with color by dimension

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/dist-flow#51]
1: Create a 2 dimensional dist plot and set color by dimension
2: Take a snapshot
3; Add snap shot to slide
Notice how the snapshot is blank

**Comment by T-Wizard** [comment]
@pernyl: I can not reproduce this. It can be that it is fixed by another fix or that I missed som step required to reproduce it

**Comment by pernyl** [comment]
@T-Wizard That is weird. I'm not doing anything other then the steps above. And I just updated the extension. I made a movie of the steps:

![!abc2](https://user-images.githubusercontent.com/29114032/132454484-52f60e4f-2b8b-45a5-95c6-50fe633a3a0e.gif)

**Comment by pernyl** [comment]
I assume you have the above app. But if you don't then let me know and you can get it
